export const translations = {
    es: {
        title: "Amigastos",
        description: "Divide gastos de manera justa entre amigos",
        addExpense: "Agregar Nuevo Gasto",
        personName: "Nombre de la Persona",
        personPlaceholder: "Ingresa el nombre",
        amount: "Cantidad ($)",
        amountPlaceholder: "0.00",
        addButton: "Agregar Gasto",
        expenses: "Gastos",
        items: "elementos",
        total: "Total",
        paymentSummary: "Resumen de Pagos",
        pays: "paga a",
        noPayments: "¡No se necesitan pagos!",
        expensesEqual: "Los gastos de todos son iguales",
        resetAll: "Reiniciar Todo",
        errorMessage: "Por favor ingresa un nombre válido y cantidad de gasto.",
        language: "Idioma",
        theme: "Tema",
    },
    en: {
        title: "Expense Splitter",
        description: "Split expenses fairly among friends",
        addExpense: "Add New Expense",
        personName: "Person Name",
        personPlaceholder: "Enter person's name",
        amount: "Amount ($)",
        amountPlaceholder: "0.00",
        addButton: "Add Expense",
        expenses: "Expenses",
        items: "items",
        total: "Total",
        paymentSummary: "Payment Summary",
        pays: "pays to",
        noPayments: "No payments needed!",
        expensesEqual: "Everyone's expenses are equal",
        resetAll: "Reset All",
        errorMessage: "Please enter valid person and expense amount.",
        language: "Language",
        theme: "Theme",
    },
};
